import tkinter
from tkinter import *
import tkinter.messagebox
def onclick1():
    tkinter.messagebox.showinfo("FEATURES","INFORMATION NOT AVALIBLE!")
def onclick2():
    tkinter.messagebox.showinfo("PURCHASES","NO PURCHASE HISTORY!")
def onclick3():
    tkinter.messagebox.showinfo("OFFERS","NO OFFERS AVALIABLE!")
def onclick4():
    tkinter.messagebox.showinfo("CONTACT US","PHONE:9876543210 \n\nEMAIL: onlinebooks@gmail.com")
def buy():
    tkinter.messagebox.showinfo("PAYMENT","PROCEED TO PAY")
def cart():
    tkinter.messagebox.showinfo("CART","ITEM ADDED TO CART!")
def comedy():
    new_window=Toplevel(root)
    new_window.geometry("3000x3000")
    new_window.title("COMEDY")
    new_window.configure(background="thistle4")
    label=Label(new_window,bg="gray24",text="COMEDY BOOKS",font=("arial",20,"bold"))
    bo1=Canvas(new_window,bg="gold",height="120",width="300",relief="ridge",bd=0)
    lb1=Label(new_window,text="BOSSYPANTS",bg="goldenrod",font=("Verdana",10,"bold","italic")).place(x=370,y=308)
    lb1=Label(new_window,text="Author: Tina Fey ",bg="goldenrod",font=("Verdana",9,"bold","italic")).place(x=370,y=332.5)
    lb1=Label(new_window,text="Year:2011",bg="goldenrod",font=("Verdana",9,"bold","italic")).place(x=370,y=359)
    but=Button(new_window,text="BUY",fg="red",bg="white",command=buy).place(x=375,y=385)
    but=Button(new_window,text="ADD TO CART",fg="red",bg="white",command=cart).place(x=420,y=385)

    bo2=Canvas(new_window,bg="pale violet red",height="120",width="300",relief="ridge",bd=0)
    lb1=Label(new_window,text="YES PLEASE",bg="maroon3",font=("Verdana",10,"bold","italic")).place(x=670,y=308)
    lb1=Label(new_window,text="Author: Amy Poehler ",bg="maroon3",font=("Verdana",9,"bold","italic")).place(x=670,y=332.5)
    lb1=Label(new_window,text="Year:2014",bg="maroon3",font=("Verdana",9,"bold","italic")).place(x=670,y=359)
    but=Button(new_window,text="BUY",fg="red",bg="white",command=buy).place(x=675,y=385)
    but=Button(new_window,text="ADD TO CART",fg="red",bg="white",command=cart).place(x=720,y=385)
    bo1.place(x=350,y=300)
    bo2.place(x=650,y=300)
    label.place(x=550,y=0)

def bio():
    new_window=Toplevel(root)
    new_window.geometry("3000x3000")
    new_window.title("BIOGRAPHY")
    new_window.configure(background="thistle4")
    label=Label(new_window,text="BIOGRAPHY BOOKS",bg="gray24",font=("arial",20,"bold"))
    bo1=Canvas(new_window,bg="gold",height="120",width="300",relief="ridge",bd=0)
    lb1=Label(new_window,text="THE LIFE OF ABRAHAM LINCOLN",bg="goldenrod",font=("Verdana",10,"bold","italic")).place(x=370,y=308)
    lb1=Label(new_window,text="Author: Henry Ketcham ",bg="goldenrod",font=("Verdana",9,"bold","italic")).place(x=370,y=332.5)
    lb1=Label(new_window,text="Year:1901",bg="goldenrod",font=("Verdana",9,"bold","italic")).place(x=370,y=359)
    but=Button(new_window,text="BUY",fg="red",bg="white",command=buy).place(x=375,y=385)
    but=Button(new_window,text="ADD TO CART",fg="red",bg="white",command=cart).place(x=420,y=385)

    bo2=Canvas(new_window,bg="pale violet red",height="120",width="300",relief="ridge",bd=0)
    lb1=Label(new_window,text="I AM MALALA",bg="maroon3",font=("Verdana",10,"bold","italic")).place(x=670,y=308)
    lb1=Label(new_window,text="Author: Christina Lamb ",bg="maroon3",font=("Verdana",9,"bold","italic")).place(x=670,y=332.5)
    lb1=Label(new_window,text="Year:2013",bg="maroon3",font=("Verdana",9,"bold","italic")).place(x=670,y=359)
    but=Button(new_window,text="BUY",fg="red",bg="white",command=buy).place(x=675,y=385)
    but=Button(new_window,text="ADD TO CART",fg="red",bg="white",command=cart).place(x=720,y=385)
    bo1.place(x=350,y=300)
    bo2.place(x=650,y=300)
    label.place(x=550,y=0)

def thrill():
    new_window=Toplevel(root)
    new_window.geometry("3000x3000")
    new_window.title("THRILLER")
    new_window.configure(background="thistle4")
    label=Label(new_window,text="THRILLER BOOKS",bg="gray24",font=("arial",20,"bold"))
    bo1=Canvas(new_window,bg="gold",height="120",width="300",relief="ridge",bd=0)
    lb1=Label(new_window,text="HOME BEFORE DARK",bg="goldenrod",font=("Verdana",10,"bold","italic")).place(x=370,y=308)
    lb1=Label(new_window,text="Author: Riley Sager ",bg="goldenrod",font=("Verdana",9,"bold","italic")).place(x=370,y=332.5)
    lb1=Label(new_window,text="Year:2020",bg="goldenrod",font=("Verdana",9,"bold","italic")).place(x=370,y=359)
    but=Button(new_window,text="BUY",fg="red",bg="white",command=buy).place(x=375,y=385)
    but=Button(new_window,text="ADD TO CART",fg="red",bg="white",command=cart).place(x=420,y=385)

    bo2=Canvas(new_window,bg="pale violet red",height="120",width="300",relief="ridge",bd=0)
    lb1=Label(new_window,text="Stranger in the lake",bg="maroon3",font=("Verdana",10,"bold","italic")).place(x=670,y=308)
    lb1=Label(new_window,text="Author: Kimberly belly ",bg="maroon3",font=("Verdana",9,"bold","italic")).place(x=670,y=332.5)
    lb1=Label(new_window,text="Year:2020",bg="maroon3",font=("Verdana",9,"bold","italic")).place(x=670,y=359)
    but=Button(new_window,text="BUY",fg="red",bg="white",command=buy).place(x=675,y=385)
    but=Button(new_window,text="ADD TO CART",fg="red",bg="white",command=cart).place(x=720,y=385)
    bo1.place(x=350,y=300)
    bo2.place(x=650,y=300)
    label.place(x=550,y=0)

root=Tk()
root.title("ONLINE BOOK STORE")
root.geometry("5000x5000")
root.configure(background="white")
C=Label(root,text="ONLINE BOOK STORE",bg="red2",font=("Algerian",20,"bold","italic"),fg="gold2",height="2",width="30",relief="raised")
C.grid(row=0,column=0)
c2=Entry(root,width=55)
c2.place(x=625,y=21)
c3=Button(root,text="CART",bg="medium violet red",font=("Verdana",8,"bold","italic"),height="2",width="13",relief="raised")
c3.place(x=1200,y=20)
lab1=Label(root,text="BESTSELLERS",bg="gray24",font=("Verdana",8,"bold","italic"),fg="white",height="2",width="30",relief="ridge")
lab1.place(x=675,y=260)
lab2=Label(root,text="NEW ARRIVALS",bg="gray24",font=("Verdana",8,"bold","italic"),fg="white",height="2",width="30",relief="ridge")
lab2.place(x=675,y=485)
search=Button(root,text="search",width="10").place(x=925,y=17)
gen=Label(root,text="GENRES",font=("Verdana",15,"bold","italic"),bd="3",bg="grey24",relief="ridge",width="15")
gen.place(x=15,y=135)
b1=Button(root,text="HOME",bg="royal blue",height="2",width="40").place(x=0,y=62.5)
b2=Button(root,text="FEATURES",bg="royal blue",height="2",width="40",command=onclick1).place(x=269,y=62.5)
b3=Button(root,text="PURCHASE",bg="royal blue",height="2",width="40",command=onclick2).place(x=539,y=62.5)
b4=Button(root,text="OFFERS",bg="royal blue",height="2",width="40",command=onclick3).place(x=809,y=62.5)
b5=Button(root,text="CONTACT US",bg="royal blue",height="2",width="40",command=onclick4).place(x=1079,y=62.5)

can1=Button(root,text="COMEDY",bg="light sea green",font=("Verdana",8,"bold","italic"),height="2",width="26",command=comedy)
can2=Button(root,text="BIOGRAFHY",bg="turquoise",font=("Verdana",8,"bold","italic"),height="2",width="26",command=bio)
can3=Button(root,text="THRILLER",bg="salmon",font=("Verdana",8,"bold","italic"),height="2",width="26",command=thrill)
can4=Button(root,text="HORROR",bg="SeaGreen2",font=("Verdana",8,"bold","italic"),height="2",width="26")
can5=Button(root,text="SCI-FI",bg="goldenrod",font=("Verdana",8,"bold","italic"),height="2",width="26")
can6=Button(root,text="ROMANCE",bg="red3",font=("Verdana",8,"bold","italic"),height="2",width="26")
can7=Button(root,text="FANTASY",bg="forest green",font=("Verdana",8,"bold","italic"),height="2",width="26") 
can1.place(x=15,y=200)
can2.place(x=15,y=250)
can3.place(x=15,y=300)
can4.place(x=15,y=350)
can5.place(x=15,y=400)
can6.place(x=15,y=450)
can7.place(x=15,y=500)
bo1=Canvas(root,bg="gold",height="120",width="300",relief="ridge",bd=0)
lb1=Label(root,text="BECOMING",bg="goldenrod",font=("Verdana",10,"bold","italic")).place(x=370,y=308)
lb1=Label(root,text="Author: Michelle obama ",bg="goldenrod",font=("Verdana",9,"bold","italic")).place(x=370,y=332.5)
lb1=Label(root,text="Year:2011",bg="goldenrod",font=("Verdana",9,"bold","italic")).place(x=370,y=359)
but=Button(root,text="BUY",fg="red",bg="white",command=buy).place(x=375,y=385)
but=Button(root,text="ADD TO CART",fg="red",bg="white",command=cart).place(x=420,y=385)

bo2=Canvas(root,bg="pale violet red",height="120",width="300",relief="ridge",bd=0)
lb1=Label(root,text="IT",bg="maroon3",font=("Verdana",10,"bold","italic")).place(x=670,y=308)
lb1=Label(root,text="Author: Stephen king ",bg="maroon3",font=("Verdana",9,"bold","italic")).place(x=670,y=332.5)
lb1=Label(root,text="Year:2011",bg="maroon3",font=("Verdana",9,"bold","italic")).place(x=670,y=359)
but=Button(root,text="BUY",fg="red",bg="white",command=buy).place(x=675,y=385)
but=Button(root,text="ADD TO CART",fg="red",bg="white",command=cart).place(x=720,y=385)

bo3=Canvas(root,bg="light sea green",height="120",width="300",relief="ridge",bd=0)
lb1=Label(root,text="ELON MUSK",bg="RoyalBlue3",font=("Verdana",10,"bold","italic")).place(x=970,y=308)
lb1=Label(root,text="Author: Ashlee Vance ",bg="RoyalBlue3",font=("Verdana",9,"bold","italic")).place(x=970,y=332.5)
lb1=Label(root,text="Year:2015",bg="RoyalBlue3",font=("Verdana",9,"bold","italic")).place(x=970,y=359)
but=Button(root,text="BUY",fg="red",bg="white",command=buy).place(x=975,y=385)
but=Button(root,text="ADD TO CART",fg="red",bg="white",command=cart).place(x=1020,y=385)

bo4=Canvas(root,bg="medium sea green",height="120",width="300",relief="ridge",bd=0)
lb1=Label(root,text="An astronauts guide to life in space",bg="seagreen",font=("Verdana",9,"bold","italic")).place(x=370,y=532.5)
lb1=Label(root,text="Author: Chris Hadfield ",bg="seagreen",font=("Verdana",9,"bold","italic")).place(x=370,y=558)
lb1=Label(root,text="Year:2019",bg="seagreen",font=("Verdana",9,"bold","italic")).place(x=370,y=584)
but=Button(root,text="BUY",fg="red",bg="white",command=buy).place(x=375,y=612.5)
but=Button(root,text="ADD TO CART",fg="red",bg="white",command=cart).place(x=420,y=612.5)

bo5=Canvas(root,bg="turquoise",height="120",width="300",relief="ridge",bd=0)
lb1=Label(root,text="THE DA VINCI CODE",bg="turquoise3",font=("Verdana",10,"bold","italic")).place(x=670,y=532.5)
lb1=Label(root,text="Author: Dan Brown",bg="turquoise3",font=("Verdana",9,"bold","italic")).place(x=670,y=558)
lb1=Label(root,text="Year:2018",bg="turquoise3",font=("Verdana",9,"bold","italic")).place(x=670,y=584)
but=Button(root,text="BUY",fg="red",bg="white",command=buy).place(x=675,y=612.5)
but=Button(root,text="ADD TO CART",fg="red",bg="white",command=cart).place(x=720,y=612.5)

bo6=Canvas(root,bg="red3",height="120",width="300",relief="ridge",bd=0)
lb1=Label(root,text="THE HOBBIT",bg="red4",font=("Verdana",10,"bold","italic")).place(x=970,y=532.5)
lb1=Label(root,text="Author: J.R.R. Tolkein",bg="red4",font=("Verdana",9,"bold","italic")).place(x=970,y=558)
lb1=Label(root,text="Year:2019",bg="red4",font=("Verdana",9,"bold","italic")).place(x=970,y=584)
but=Button(root,text="BUY",fg="red",bg="white",command=buy).place(x=975,y=612.5)
but=Button(root,text="ADD TO CART",fg="red",bg="white",command=cart).place(x=1020,y=612.5)

bo1.place(x=350,y=300)
bo2.place(x=650,y=300)
bo3.place(x=950,y=300)
bo4.place(x=350,y=525)
bo5.place(x=650,y=525)
bo6.place(x=950,y=525)

quote=Label(root,text="BOOKS ARE A UNIQUELY PORTABLE MAGIC!",bg="yellow",font=("Algerian",20,"bold","italic"),fg="OrangeRed2",height="4",width="60",relief="raised")
quote.place(x=300,y=110)
root.mainloop()

